on: push
name: Transfer Files
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: FTP-Deploy-Action
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
       SSH_PRIVATE_KEY: ${{ secrets.-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEAnUwokYnWpXBF+Zbgd9xl0tKwZeE5ZmRNa3H17eYJ4zbk+Lkd
XAnJGs56kzB+IHKZi+RY/oANWo4/42By794YUbdiO4kayHyp2kLwzcVm1L73gkuX
8ESK9tLCvrN5Us2k5T4abWU9K0cVNJrgnjhzL8h8qjFHcebTtvRj7obM7M3AAutj
R+1nBIL0QqFwBo9Zu7DPm4GT9+gykmnzsLkWdrTh/20weYL+rXTxhp0StMBlpEAM
jxsWUUu3jDQCYc95TjA2903dAOhVSiOrbRcn+LAAiNthFQpWl6xTnxh1Yf4Q+/PE
7DgcAVw812j50kRGrexbSVLiiEQcT7PsS/bzqoiVbK+2g1mselvLgQ6Ma+A6arcI
/GRFsVVjUtOaA1irHObJF+sSkPypjNuXELeH15yWgKhkYgzKINPrAqMbhVObsezD
AtoB2CT4+b07OUxlHoEagIONb0RTUBMOehpnSDLAGAmrKBmIOIzKN1j62jVqPUq6
8CIOlHOkjT1i28b0ueacXImeJhuf1NlOGLRhojVJo1g6NPExud5F+dZ8jcYeayzn
xth9LGwKSt7GioXWyXp1OAYj6443X8deWPK7XziohA7K5i2GoGleClUKhQBEfQnF
yL1hiwLCYZ23+huR0M5TWoSB0eGHgte1cMziIkTm+uuYmtyYhUMWxG0ET1kCAwEA
AQKCAgAjXRHp1oFpZFp3CJKin+xMf42k+gO7n2VAeLh/qa4jZR4JRSTyokiSPEWW
fdp9VQZsSwQvA379EuoOJorwno/9Hyt4kxRwaoaNSWt196FsxxpCMtiP7fkIEM4z
rYnjMdSWrWWnnpEn/60mzIMfTzWmUn6kjLuxQeHrSfqFj8zWmFNI1L7XVupIO2DK
8hyLfQMBjXi/T1yC6bMk86kT3CjOu0/r6xJw3yB+wsHiL8Ia3P589OFd8wsLb+hu
HutCLjDpgTF6XAkJwTIbnvVVa1VTNc6I9jlXT6G0K8wJAqixRTtwSZfGO78gFyqe
iz1PJoZ1Z6QGUhoX5KgwyxSe54BURmlLN9j43QaTqiXu67z5A29/svNBBpZBScVb
bbIq8i3CCf0xid77Q1qbu3NAtWz7CmH337mBfa2AP8FC4J+c0JgsPTKaoSwDMss7
vXXj0Xq8WUU0B6ZlUMklt+DMZL6Z9CuMPr70RolA+LSy+tFXIPhmqL4JYZ8A+Qqd
d7dt1xSt7Wk2wpElPZspBn13urSinyxCCj0H3KDnJa/HoPa/WoSX5QApQEKkj9GK
pJjpelEQEkyBB4W7E2JY1OTI7X3drZpB+KTdHf7UMWtb9EgWcaWTxjTc6rRlyPmG
Za5tWOXuZMJoZwbK5co6FnCZpbMlAWue6LVA3hjJ6xToC9BAAQKCAQEAzjQEjITm
5QY1Nm8QmDhFFMCOlBmkLLFrRS25RlmoBLDcH8uFv2+IOgHV8gjKzb2vAikWP+L9
O8a2lCZ1+VyH6r6s1Q1CDtn6nIht2/9BRclE8kdJw8xcgXheLRgzySvTFebOsRVS
A60t0hzuj4EQYZCqqs2IWOMqV6CjAUqD20AXUi939bIyyfXsV6kF2w/55yXqVPeE
jtkolrsJrBsBCKX4sKVG3pJDBbBQVtX+XaKiyRLc6Ppim2kT+/kpsDcf/B1tdEk6
Kd9Yr3tAHVqCnGOLgfo80CEZppzH5zmJHz7FPsMBQoc/IsD4pn8TClb4TklEUTJ2
tKcy3BR4ELHkAQKCAQEAw0ir6f4ifBh62y2CQnv2I2sSVoV/c75A2bX6hPzuc59G
YFqIxQMqoqcspI+OWrJHDg5wzrb03hjApkCy2tay5yktK3fDTKf7BXYHDhFPFZxo
qA+e6dQZaZw/eeqp4ftMMvVJlYzInISyo8hcFNeLKy8HQlWvyvhJnijYTFehTY0k
XilWNnJvQfMvH6R6pJAUT2j1Hu/y1Mw3ygLe6racda3H1l1JlfrQDzKiVY99nEIC
bOrmCs0gH9nu9PZfEgb0XEVRjtDwmFAgAMhkIStJxTY6nM65WhlpGbe7tjObkMl7
5OUVKI5dSk9rosMQ0bclBOMjHsq/owgVJCLxemALWQKCAQBF9ZoRfsnDrD6DkF0F
+Blf+BCnqKdtzmgBmYjBmIuLw+F7HBbto06Jt7O5oUgFU7S7u+rjlASssjehvgbK
qp0mhLiotA3Ucho334W+XTTtE2ND+/HH7173QjpZfFudhjPgu2Um6X/g5XGlVtGN
eJFxOJ7ewkrfNXtZLZQATSK9UVpYNOizQFlA8iHUf/EPqLT1uoRtfWjI+l5t/VlD
vgm0wHLGo9yOiPsaQ/6N556ccCBgrfirRsAL0DPKinedZKaCaA2JpYqJSFCTgPJ4
wwuLOa7MU3Use/5y68Ba78dZBXfwWkLkKnS+OtBh1L1GBcnK7cqy7bcehZeY2Yz+
xQwBAoIBACcCyXUBE5p+uWw3dyIY6V7B8PPfz0or44CaXeVbMbdfRgvRiijxLP85
Li3hj6qGmrMwJ1DkM556i2Gq4w/ce/i5vRBF6HnTxM2eemJRCt9iU3XfSPulJz51
vCh6vF0selhjr8N0UE8UIyucxuhS9rY1utmBjJCbcPlrZ2o4xzxayb0VvOc7jQY7
slo73VQqhCQo726yuGvSMALm9+kjebX4dUdZc23GoPGoR82X0Jv6g8mGU1YtDBHQ
02+UGAHd6crU/inti2Kh/wKpBXeq0h3Xa3YPxe89zEUa8yC+xoDx/xIGwWdMqU5C
91mYZi++ymJjjYyFLCtBXhfN8zdjIGECggEAX4xT7QRswG+tQMwl9/hBguW1k9l7
ZBJG3CYA301UDIQSG+yI1qoN+3cs2Hp1AOAruD0euCuXG9x7zah8jWpWe66A+7ul
0upChn/zehdS5ePgj0rMjwd+2xQEdkXS5HhYUAwflNuf0SEwUBuNuFolDs4abzM+
I6yW9TM9HAmbRAlRASjHojASga1L7nod37Fmqq5qr1pBOwcoJm4J6bWSo/2F/1xa
SXVh1be7gM06+kcqJOKhbPEGwVmgbQW+DqickfPBzDLJYeu8SWBvqjoVWM7pV4IF
BRe2k16quMgrgYCDpo6Iofb3dl9ud4NSdMrgABj4gB5UR3LYSjyn5DSISA==
-----END RSA PRIVATE KEY----- }}
       SOURCE: "./"
       REMOTE_HOST: ${{ https://cicd.datanethosting.com }}
       REMOTE_USER: ${{ cicddatanethosti }}
       TARGET: ${{ secrets.REMOTE_TARGET }}
