on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRETS }}
          REMOTE_HOST: 35.154.14.181 	
          REMOTE_USER: ec2-user
          REMOTE_PORT: 22
          SOURCE: "./"
          TARGET: /home/ec2-user/test
 
