on: push
name: Transfer Files
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: FTP-Deploy-Action
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
       host: https://cicd.datanethosting.com 
       user: cicddatanethosti
       password: ut81WRD+MgPg
       SOURCE: "./"
