on: push
name: Transfer Files
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
         key: secrets 
         known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H secrets.SSH_HOST  >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./ cicddatanethosti@SSH_HOST :/home/cicddatanethosti/public_html
