on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRETS }}
          REMOTE_HOST: cicd.datanethosting.com
          REMOTE_USER: cicddatanethosti
          REMOTE_PORT: 22
          SOURCE: "./"
          TARGET: /home/cicddatanethosti/public_html
 
